# Generated by Django 2.2.13 on 2020-06-15 07:31

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('liked_under60', models.IntegerField(default=0)),
                ('liked_1960', models.IntegerField(default=0)),
                ('liked_1970', models.IntegerField(default=0)),
                ('liked_1980', models.IntegerField(default=0)),
                ('liked_1990', models.IntegerField(default=0)),
                ('liked_2000', models.IntegerField(default=0)),
                ('liked_2010', models.IntegerField(default=0)),
                ('liked_2020', models.IntegerField(default=0)),
                ('liked_adventure', models.IntegerField(default=0)),
                ('liked_fantasy', models.IntegerField(default=0)),
                ('liked_animation', models.IntegerField(default=0)),
                ('liked_drama', models.IntegerField(default=0)),
                ('liked_horror', models.IntegerField(default=0)),
                ('liked_action', models.IntegerField(default=0)),
                ('liked_comedy', models.IntegerField(default=0)),
                ('liked_history', models.IntegerField(default=0)),
                ('liked_western', models.IntegerField(default=0)),
                ('liked_thriller', models.IntegerField(default=0)),
                ('liked_crime', models.IntegerField(default=0)),
                ('liked_documentary', models.IntegerField(default=0)),
                ('liked_sciencefiction', models.IntegerField(default=0)),
                ('liked_mystery', models.IntegerField(default=0)),
                ('liked_music', models.IntegerField(default=0)),
                ('liked_romance', models.IntegerField(default=0)),
                ('liked_family', models.IntegerField(default=0)),
                ('liked_war', models.IntegerField(default=0)),
                ('liked_tvmovie', models.IntegerField(default=0)),
                ('liked_recents', models.CharField(default='', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
