<<<<<<< HEAD:accounts/migrations/0002_auto_20200612_1205.py
# Generated by Django 3.0.7 on 2020-06-12 03:05
=======
# Generated by Django 2.2.13 on 2020-06-12 04:05
>>>>>>> 0612_jongwoo:accounts/migrations/0002_auto_20200612_1305.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:accounts/migrations/0002_auto_20200612_1205.py
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('community', '0001_initial'),
=======
        ('auth', '0011_update_proxy_permissions'),
        ('community', '0001_initial'),
        ('accounts', '0001_initial'),
>>>>>>> 0612_jongwoo:accounts/migrations/0002_auto_20200612_1305.py
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_articles',
            field=models.ManyToManyField(related_name='liked_users', to='community.Article'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
